### ISSUE TITLE
Markdown support in recipe text box?

### ISSUE THREAD

**Issue by Jezz3** [aimok04/kitshn#1]
Hey, it would be nice to have the text in the recipe to support Markdown syntax like ** text** for bold.
In the webinterface, rhe recipe text supports Markdown.
Thanks for this creat app. Looks really nice

**Comment by aimok04** [comment]
Hi, thanks for mentioning it 😊. This is going to be added in the next release!

**Comment by Jezz3** [comment]
Thank you, just got the update and it works nice :)
