### ISSUE TITLE
Display videos associated with the steps

### ISSUE THREAD

**Issue by aimok04** [aimok04/kitshn#15]
> It would be cool to display ~the image~ or the video associated with the step, just like the web version (except that the web version does not display the videos, at least for me)

_Originally posted by @dertasiu in https://github.com/aimok04/kitshn/issues/14_

split issue because implementing video is more difficult

**Comment by aimok04** [comment]
Hi @dertasiu 👋
This feature is also implemented now. You'll need to include "video" somewhere in the file name if you want to use it (e.g. "video_step_one.mp4") because the Tandoor api does not disclose the file type before download.

**Comment by dertasiu** [comment]
Amazing! I will be updating all my recipes and get back to you!.
Thank you!!

**Comment by dertasiu** [comment]
It works very well!
I just changed the names with this SQL query to concat "video_" to the name of every .mp4 file in the database. 
`UPDATE cookbook_userfile SET name = concat('video_', name) WHERE file LIKE '%mp4';`
It's a bummer that tandoor doesn't expose the extension of the file or the MIME type in the API, but this solution is more than enough.
Thank you very much!
