### ISSUE TITLE
Unallocated Ingredients Always Displayed

### ISSUE THREAD

**Issue by wirerydr** [aimok04/kitshn#16]
kitshn version:  1.0.0-alpha 7 (106)
Tandoor version: Tandoor (HEAD) 1.5.19 - commit 1bfe5bb6a031b7b2a03c0471adfa8245ce0476f1

Hello there.  Testing out Tandoor, and also kitshn.  Liking kitshn far more than the stock web UI in Tandoor.  But I've come across an issue that I can't get to the bottom of.

After creating several recipes within Tandoor, I try to view them with kitshn.  In all cases, each recipe shows the red "Unallocated ingredients" warning.  Tapping on it shows the list of ingredients, with unchecked checkboxes beside each one, and a set of steps at the bottom (with step 1 pre-selected).

There seems to be no way to resolve the "Unallocated ingredients" warning.  I've tried selecting all the ingredients, and then tapping the "save" icon in the top-right.  The app then shows "Saving", after which it goes back to the recipe screen - which STILL shows "Unallocated ingredients".

If I instead select only several of the ingredients and then save them, I get a popup warning that several ingredients still need to be allocated.

I've tried killing the app (kitshn), and restarting it - no change.  I've tried refreshing it - no change.  I've tried with several different recipes within Tandoor - no change.  I have a recipe with a step that has "Hide Step Ingredients" checked, and another recipe with that unchecked.  Seems to have no impact.

I then tried examining open/closed issues for both kitshn and Tandoor, in case this was previously reported, but I can find no reference.

Any ideas what I am doing wrong, or what I might need to do to fix this?

Thanks for what looks to be shaping up as a great android app!

**Comment by aimok04** [comment]
Hi! First of all, thx for your nice words 😊

---

The "Unallocated ingredients" warning will only show when where are
  1. multiple steps
  2. all ingredients added to the first step

(at least how I remember it — I will check later if it really works like this). 
This is f.e. meant for imported recipes.

This is may be a bit of a design flaw, since there could be recipes where this is intended.

---

The ingredient allocation dialog should work like this:
1. Select all ingredients you want to allocate to the currently selected step
2. Move to the next step by either swiping right or clicking on the number in the bottom bar
4. Repeat 

---

At the moment kitshn completely ignores the "Hide Step Ingredients" value so it's expected to make no difference, might change that in the future.

---

Please let me know if this resolves your issue. 
I will add an ignore button to the "unallocated ingredients" warning. If the warning really annoys you, a workaround would be to add a header ingredient to any other step other than the first one.

**Comment by wirerydr** [comment]
Thanks for the very quick response. I can confirm that reducing the recipe to only have one step removes the "Unallocated ingredients" warning. So it's behaving as you recall.

I'm unsure what a "header ingredient" is so I didn't explicitly test your suggested workaround. I did add back in a empty 2nd step to confirm the warning reappeared (it did). I then added a blank ingredient to that step (no amount, food, unit or note). This renders ok in Tandoor itself, but in kitshn it shows up under the 2nd step as a blank ingredient line with the default "g" unit.

I can see how this warning could be useful when importing recipes into Tandoor. However I would also personally prefer to use Tandoor's built-in step functionality rather than use single steps, even if they contained bulleted / numbered lists. A feature to either ignore it on a per-recipe basis, or an app setting to suppress the check entirely would be greatly welcomed - probably the former as it provides more flexibility to the user.

Thank you again for your work on the app!

**Comment by aimok04** [comment]
![Kooha-2024-09-22-16-28-28](https://github.com/user-attachments/assets/f1fbee99-63a6-4864-b7e6-0414dac7332e)

Normally this can be used to "group" ingredients.
Probably going to come up with a solution for alpha.9 :)

**Comment by wirerydr** [comment]
Ah hah - OK, I tried adding a 2nd step and then adding to it a header ingredient.  That indeed works as far as kitshn goes - the warning disappears, and the steps are properly rendered.

It messes up the rendering within the Tandoor app's web-interface itself ([screenshot](https://imgur.com/a/Di6BKaN)), but given how nicely kitshn is shaping up, this isn't a problem for me.  As a workaround, this is fine.

Thanks!

**Comment by aimok04** [comment]
> Probably going to come up with a solution for alpha.9 :)

Welp, I had some spare time, so I added both options :)
It's going to be in the next release (alpha.8)

**Comment by wirerydr** [comment]
Tested the two new options:

1. Enabled the global setting.  Result:  Correctly suppressed the warning.
2. Diabled the global setting.  Result:  Correctly displayed the warning.
3. With the global setting disabled, clicked "ignore" on the warning itself.  Result - warning disappeared.
4. Killed the application, restarted it, and observed that the warning was correctly no longer shown on that one recipe.  Also, the warning correctly continued to show for a separate recipe with multiple steps.

TYVM for the very quick fix!
