### ISSUE TITLE
Support for templating

### ISSUE THREAD

**Issue by lukasspettel** [aimok04/kitshn#25]
I am using the templating feature in tandoor to increase readability of the instructions. Supporting templating in the app would be great.
https://docs.tandoor.dev/features/templating/

Here is how it's displayed in the web version of tandoor: 

![Screenshot 2024-10-25 123410](https://github.com/user-attachments/assets/6c4e924e-180b-4abf-8fa2-bd9f7d3be4a0)

Here is how it's currently displayed in the app: 

![Screenshot 2024-10-25 123548](https://github.com/user-attachments/assets/8c576d65-a67c-48be-a69e-d9d6b8bea587)

**Comment by aimok04** [comment]
Hey @lukasspettel 👋

I've added support for basic templating by using regex. I did test this and it worked fine for me, but feel free to give feedback once you get to try this out :)

The next release will be on Sunday.

**Comment by lukasspettel** [comment]
Thank you very much for adding this feature so quickly! I'm looking forward to try it. :)

**Comment by lukasspettel** [comment]
Hey @aimok04, I did update the app on play store and then the recipes weren't loading anymore. I did try to reinstall and reconnect to my server but now the recipes are not displayed at all. In the server settings page the tandoor version of my server is also listed as unknown ("Unbekannt").

**Comment by aimok04** [comment]
Hi! Can you load other pages f.e. the shopping list or the recipe books page? And does the app show an error or is the home page just blank? 

You could try downgrading (either with [GitHub releases](https://github.com/aimok04/kitshn/releases/tag/v1.0.0-alpha.9) or by using [F-Droid](https://f-droid.org/packages/de.kitshn.android/)) and see if it still works on an older version.

Could you also tell me which version your Tandoor server is running?

**Comment by aimok04** [comment]
Oh or is it just the recipe "details" page? If so, would you mind exporting and sending me a recipe where this happens to you?

**Comment by lukasspettel** [comment]
The shopping list, shopping and meal planning tab works fine. The recipe overview page is empty with a message that this recipe couldn't be found ("Dieses Rezept konnte nicht gefunden werden"). However when I try to access the recipe in the meal planning feature it just displays the content placeholder animations: 

![Screenshot_20241028_151750_kitshn](https://github.com/user-attachments/assets/203f4bc6-e457-466e-b686-a89a1a3d5c20)

I'm running tandoor v.1.5.19. When downgrading the app manually to alpha9 everything is working fine again.

**Comment by aimok04** [comment]
Welp, it's loading normally for me 🫠
Could you also send me the recipes that are linked to this recipe?

Does this happen with all of your recipes or are there any exceptions?

**Comment by aimok04** [comment]
Ok I know why it's loading for me. The properties you've set for the individual foods are not exported with the recipe, so the problem probably lies there. I think I could solve this when you just send me the API response, not the other recipes.

**Comment by lukasspettel** [comment]
Here is the json API resonse: 
[api_response_recipe.json](https://github.com/user-attachments/files/17553607/api_response_recipe.json)

**Comment by aimok04** [comment]
Good news: I think I have found this issue 🥳
Gonna release this in a moment …

**Comment by aimok04** [comment]
@lukasspettel FYI: The patch was reviewed and is now also available on Google Play.

**Comment by lukasspettel** [comment]
I've tested it and it now works perfectly, thank you very much for your efforts and amazing work!
