### ISSUE TITLE
Ingredient "Copy Template Reference" doesn't work with multiples in a row

### ISSUE THREAD

**Issue by blknight88** [aimok04/kitshn#27]
If I have instructions that list multiple "Copy Template Reference" from ingredients in a row on one line, it only shows the first one. 

**Example:**
Make the miso marinade. 
Combine {{ ingredients[0] }}{# white miso paste #}, {{ ingredients[1] }}{# reduced sodium soy sauce #}, {{ ingredients[2] }}{# ginger paste #}, {{ ingredients[4] }}{# granulated sugar #}, {{ ingredients[3] }}{# mirin #}, {{ ingredients[5] }}{# sesame oil #}, {{ ingredients[6] }}{# garlic #}, and {{ ingredients[7] }}{# kosher salt #} in a medium bowl, then whisk. 

**In the webpage it outputs the correct information:**
Make the miso marinade. Combine 0.25 cup white miso paste, 2 tbsp reduced sodium soy sauce, 1 tbsp ginger paste, 1 tbsp granulated sugar, 1 tbsp mirin, 2 tsp sesame oil, 2 cloved garlic, and 1 tsp kosher salt in a medium bowl, then whisk. 

**In the app it shows this:**
Make the miso marinade. Combine 0.25 cup white miso paste in a medium bowl, then whisk.

**Comment by aimok04** [comment]
Hi!
Thanks for opening this issue. This is happening because of the way comments get parsed in the app, but it was a pretty easy fix. 
I am going to release this next Sunday at the latest!

**Comment by blknight88** [comment]
hello, no problem, thanks for fixing it so fast!

**Comment by aimok04** [comment]
Hey @blknight88 👋

Decided to release this as a hotfix, so this issue is hopefully solved with version **1.0.0-alpha.12.1**!
