### ISSUE TITLE
Working with Authentic / SSO

### ISSUE THREAD

**Issue by pathofleastresistor** [aimok04/kitshn#30]
As someone who uses Authentik to login into Tandoor, I can't get past the first screen where I enter the URL.

**Comment by aimok04** [comment]
Hi, haven't thought about that yet.
Authentik just wraps around the app right? Or does it replace the login functionality in some way?

**Comment by aimok04** [comment]
@pathofleastresistor @jvanbruegge

I've added an option to log in with web view. Probably releasing this on Sunday.
If you want, you can try it out in the [nightly release](https://github.com/aimok04/kitshn/releases/tag/nightly).

Feel free to reopen if you encounter any problems :)

**Comment by aimok04** [comment]
There have been some problems with some requests (mostly creating/modifying) not working, so I reopened this for the time being.

**Comment by Akruidenberg** [comment]
Tested. Works fine with Authentik 2024.08!

**Comment by aimok04** [comment]
@Akruidenberg 
Nice, thanks for testing 👍

**Comment by aimok04** [comment]
>  Only add button did not work.


Did you use the nightly version released ~ 5h ago or the version before that? I thought I already solved that problem😅

**Comment by Akruidenberg** [comment]
> > Only add button did not work.
> 
> Did you use the nightly version released ~ 5h ago or the version before that? I thought I already solved that problem😅

Thanks! Latest nightly works perfectly with the add button.
