### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by tmeuze** [aimok04/kitshn#39]
Hi, silly question here. 

How does one go about installing the iOS app? I imagine it isn't published (don't blame you for not wanting to pay for dev license). Do we need to build it in Xcode or is there an IPA binary available?

Thanks!

**Comment by aimok04** [comment]
Hi, not a silly question at all!

I was a bit too quick with updating the README  and the about text; the iOS app is buildable through xcode, but it is still quite experimental 😅

I am planning to release IPAs regularly once I think it's finished enough. I also want to make a source for the Alt store:)

**Comment by tmeuze** [comment]
Thank you very much!

**Comment by aimok04** [comment]
Hey @tmeuze

 The [latest release](https://github.com/aimok04/kitshn/releases/tag/v1.0.0-alpha.15) contains an .ipa and there is also a source for AltStore/SideStore available at https://altsource.kitshn.app :)

**Comment by tmeuze** [comment]
@aimok04 It works so well! Been missing that Material You goodness since switching. Thanks for all your work!
